#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 27 08:37:09 2017

Lab 6. 
  . Main objective: creating and working with lists.
  . Other objecives: working with random numbers, defining and calling function

@author: Alvaro Monge alvaro.monge@csulb.edu
@author: Cesar Hernandez hernandezcesar746@gmail.com 
@author: Mario Bajenting mariobajenting@gmail.com
"""

import random   # module defining functions to generate random numbers

made = [] 

def generate_random_values(length, mean, standard_deviation):
    
   '''(int, float, float) 
   
      Returns a list of random float values from a Gaussian distribution.
      
      Args:
         length: the length of the list (the number of values the list is to contain)
         mean: the mean value of the Gaussian distribution
         standard_deviation: the standard deviation of the Gaussian distribution
      Returns:
         A list of float values from a Gaussian distribution with given mean and standard deviation
   '''
   
   # TODO: below this comment, enter the instruction used to create an empty list
   #       that is to be used in the rest of this function
   
   #made = []

   # TODO: Next, design and write a loop that generates random float values and 
   #       adds these to the list. The float values should come from a Gaussian 
   #       distribution
   # If needed, see section 3.2 on adding elements to a list
   # Also, see: https://docs.python.org/3/library/random.html#random.gauss

   i = 0
   while i < length:
        made.append(random.gauss(mean, standard_deviation))
        i += 1
        
   return made

#    TODO: The last instruction of this function should return the list of values
#   i = 0
#   made_sum = 0
#   while i < length:
#       made_sum += made[i]
#   
#   made_average = made_sum/length
  
# main ... the instructions after all function definitions

''' TODO: call the function to create a list of 25 values from a Guassian distribution
       with a mean of 80 and a standard deviation of 10.5. Context: each value in the list 
       represents a grade. Use a loop to print the first list in reverse order (from the 
       last element to the first) and to find the average of these values. Print the average.

'''


#while made.len

print ("list 1: ", generate_random_values(25, 80, 10.5))



print ("list 1 reversed: ", generate_random_values(25, 80, 10.5))


''' TODO: call the function to create a second list. This list should have 10 values,
      with a mean of 159.8 and a standard deviation of 7.5. Use loops to print all the
      values and to find the average of these values. Print the average.
'''

print ("\nlist 2: ", generate_random_values(10, 159.8, 7.5))
